# Opciones de Gradle para todo el proyecto.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# Usar las librerías AndroidX en lugar de las antiguas de soporte.
android.useAndroidX=true
# Cada R solo contiene los recursos propios del módulo (compilación más rápida).
android.nonTransitiveRClass=true
